source 'https://rubygems.org'

gem 'jekyll'

gem 'rouge', github: 'pyrmont/rouge', branch: 'master'
gem 'commonmarker-pluggable', github: 'pyrmont/commonmarker-pluggable', branch: 'master'

group :jekyll_plugins do
  gem 'jekyll-commonmark'
  gem 'jekyll-github-metadata'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-paginate'
  gem 'jekyll-seo-tag'
end
