source 'https://rubygems.org'

gem 'jekyll'
gem 'rouge'

# gem 'rouge', github: 'pyrmont/rouge', branch: 'bugfix.janet-unmatched-parens'

group :jekyll_plugins do
  gem 'commonmarker-pluggable', github: 'pyrmont/commonmarker-pluggable', branch: 'master'
  gem 'jekyll-commonmark'
  gem 'jekyll-github-metadata'
  gem 'jekyll-last-modified-at'
  gem 'jekyll-paginate'
  gem 'jekyll-seo-tag'
end

group :development do
  gem "webrick"
end
